#!/usr/bin/env bash
# This is a Bash script that displays the content of the current directory in a list format where only the part of the name after the first dash is displayed by using for loop  and do not display hidden files.

echo "Contents of the current directory are : "
for file in *; 
do
if [ -f "$file" ] && [[ "$file" != .* ]]; 
then
name_after_dash=$(echo "$file" | cut -d '-' -f 2-)
echo "- $name_after_dash"
fi
done
