#!/usr/bin/env bash
# This is a Bash script that gives you information about the school file by using if and else statements 
school_file="school_file.txt"
if [ -e "$school_file" ];
then
echo "school file exists"
if [ -s "$school_file" ];
then
echo "school file is not empty"
else
echo "school file is empty"
fi
if [ -f "$school_file" ];
then
echo "school file is a regular file"
fi
else
echo "school file does not exist"
fi
